/**
 * Dart → TS cross-language Noise IK interop test.
 *
 * Loads a fixture generated by `shepaw/tool/generate_interop_fixture.dart`
 * (Dart as the ground truth) and verifies:
 *
 *   1. The TS responder can decrypt the Dart initiator's msg 1, recovering
 *      the same payload and peer static pubkey.
 *   2. The TS responder, when fed the Dart-computed msg 2 bytes directly,
 *      AND using the same ephemeral as Dart's responder, produces matching
 *      transport keys. (Can't test this with noise-protocol@3 because it
 *      refuses to accept pre-set ephemerals for IK. Skipped with rationale.)
 *   3. The TS initiator can decrypt the Dart responder's transport
 *      ciphertext. (Requires matching transport keys on both sides, which
 *      requires the TS side to see the exact handshake Dart saw.)
 *
 * The test that DOES run, and is the critical interop proof, is #1: if
 * BLAKE2b, HMAC-BLAKE2b, HKDF, X25519 DH, ChaCha20-Poly1305 AEAD, and the
 * SymmetricState mix sequence don't match on both sides, the AEAD tag in
 * msg 1 won't verify. A successful decryption means the two implementations
 * agree on every primitive and on the handshake hash evolution up through
 * the `ss` DH step.
 *
 * Combined with the TS→Dart test (Dart responder consuming TS-generated
 * msg 1) on the other side of this pair, we have bidirectional proof that
 * the handshake prefix is interop-correct.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import noiseLib from 'noise-protocol';
import cipherStateFactory from 'noise-protocol/cipher-state.js';
import cipherFactory from 'noise-protocol/cipher.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

interface Fixture {
  suite: string;
  prologue_hex: string;
  initiator: {
    static_private_hex: string;
    static_public_hex: string;
    ephemeral_private_hex: string;
    ephemeral_public_hex: string;
    msg1_payload_utf8: string;
    msg1_hex: string;
  };
  responder: {
    static_private_hex: string;
    static_public_hex: string;
    ephemeral_private_hex: string;
    ephemeral_public_hex: string;
    msg2_payload_utf8: string;
    msg2_hex: string;
  };
  transport: {
    init_to_resp_plaintext_utf8: string;
    init_to_resp_ciphertext_hex: string;
    resp_to_init_plaintext_utf8: string;
    resp_to_init_ciphertext_hex: string;
  };
}

const fx: Fixture = JSON.parse(
  readFileSync(
    resolve(__dirname, 'fixtures/noise_interop_fixture_dart_to_ts.json'),
    'utf-8',
  ),
) as Fixture;

function hex(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

describe('Dart→TS Noise IK interop', () => {
  it('suite matches', () => {
    expect(fx.suite).toBe('Noise_IK_25519_ChaChaPoly_BLAKE2b');
  });

  it('prologue decodes to "shepaw-acp/2.1"', () => {
    const p = hex(fx.prologue_hex);
    expect(new TextDecoder().decode(p)).toBe('shepaw-acp/2.1');
  });

  it('TS responder decrypts Dart-generated msg 1 byte-for-byte', () => {
    // Set up a TS responder with the fixture's long-term responder static keypair.
    const rKp = {
      publicKey: hex(fx.responder.static_public_hex),
      secretKey: hex(fx.responder.static_private_hex),
    };
    const prologue = hex(fx.prologue_hex);

    // Use the raw noise-protocol API directly (our NoiseSession.responder
    // takes an AgentIdentity but we have raw bytes here — either path works).
    const hs = noiseLib.initialize('IK', false, Buffer.from(prologue), rKp);

    const msg1 = hex(fx.initiator.msg1_hex);
    const out = Buffer.alloc(msg1.length);
    let split: { tx: Uint8Array; rx: Uint8Array } | undefined;
    expect(() => {
      split = noiseLib.readMessage(hs, msg1, out);
    }).not.toThrow();

    // IK responder doesn't split after msg 1.
    expect(split).toBeUndefined();

    const payloadLen = noiseLib.readMessage.bytes;
    const payload = out.subarray(0, payloadLen);
    expect(new TextDecoder().decode(payload)).toBe(fx.initiator.msg1_payload_utf8);

    // The handshake state now has the initiator's static public key in `rs`.
    // Cross-check it against the fixture.
    const learnedRs = (hs as { rs?: Uint8Array }).rs;
    expect(learnedRs).toBeDefined();
    expect(Buffer.from(learnedRs!).toString('hex')).toBe(fx.initiator.static_public_hex);
  });

  // The next two tests would prove full transport-key interop — they require
  // driving the TS responder's handshake with the fixture's responder
  // ephemeral, which `noise-protocol@3` does not support for IK. Leaving them
  // as documentation of what would close the loop if we either switch libs or
  // add our own thin IK implementation on the TS side.

  it.skip('TS responder produces the same msg 2 bytes as Dart (requires ephemeral injection)', () => {
    // Would require: noise.initialize('IK', false, prologue, rStatic, rEphemeral)
    // with rEphemeral honoured. noise-protocol@3 rejects this.
  });

  it.skip('TS responder decrypts Dart-generated transport frame (requires ephemeral injection)', () => {
    // Same dependency as above. Transport keys depend on both ephemerals;
    // without injecting, the TS-side handshake state has different keys
    // than Dart's, so it can't decrypt Dart's ciphertext.
  });

  // Silence unused — we import cipherStateFactory/cipherFactory to keep the
  // dependency declaration explicit; the skipped tests above would use them.
  it('imports additional crypto primitives without crashing', () => {
    const cs = cipherStateFactory({ cipher: cipherFactory() });
    expect(cs.STATELEN).toBe(40);
  });
});
